name: shell commands

on: [push]

jobs:
  run-windows-commands: 
    runs-on: widnows-latest
    steps:
      - name: date
        run: date
      - name: Directory Bash
        run: pwd
        shell: bash
