name: shell commands

on: [push]

jobs:
  runs-shell-commands:
     runs-on: ubuntu-latest
     steps:
     - name: echo a string
       run: echo "Hello String"
     - name: multiline 
       run: |
           node -v
           npm -v